### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by euskadi31** [freshprince/weechat-fish#11]
```
Traceback (most recent call last):
   File "/Users/euskadi31/.weechat/python/autoload/fish.py", line 645, in fish_modifier_in_privmsg_cb
     clean = blowcrypt_unpack(match.group(5), b)
   File "/Users/euskadi31/.weechat/python/autoload/fish.py", line 276, in blowcrypt_unpack
     raw = blowcrypt_b64decode(padto(rest, 12))
   File "/Users/euskadi31/.weechat/python/autoload/fish.py", line 241, in blowcrypt_b64decode
     right |= B64.index(p) << (i * 6)
 ValueError: substring not found
 erreur dans la fonction "fish_modifier_in_privmsg_cb"
```

**Comment by jpgninja** [comment]
Apologies for dragging this out of the pits of history, but I'm having the same error, 8 years later and am wondering what I'm doing wrong. Here's the error, for the updated line numbers:

		Traceback (most recent call last):
		  File "/Users/user/.weechat/python/fish.py", line 865, in fish_modifier_in_privmsg_cb
		    clean = blowcrypt_unpack(match.group(5), b)
		  File "/Users/user/.weechat/python/fish.py", line 460, in blowcrypt_unpack
		    raw = blowcrypt_b64decode(padto(rest.encode('utf-8'), 12).decode('utf-8'))
		  File "/Users/user/.weechat/python/fish.py", line 414, in blowcrypt_b64decode
		    right |= B64.index(p) << (i * 6)
		ValueError: substring not found

		=!= python: error in function "fish_modifier_in_privmsg_cb"

Other than that, I've gathered so far that the lack of the `substring` is getting flagged from blowcrypt/pycrypto, not the plugin since the term `substring` doesn't appear in the file.

Others have had [similar issues](http://5.9.10.113/26595855/python-irc-fish-encryption-issue) but in all cases there are no answers which leads me to believe there's something obvious I'm overlooking which, in the past, the questioner has thought [_"oops, that was obvious"_](https://media.giphy.com/media/COYGe9rZvfiaQ/giphy.gif) and simply removed or self-closed their issues, but I'm happy to be the proud dodo bird who leaves it up for future dodo birds.

I'm using `weechat` on macOS Big Sur (11.4).
