### ISSUE TITLE
"ValueError: substring not found" in fish_modifier_in_privmsg_cb() using Python 3

### ISSUE THREAD

**Issue by jpgninja** [freshprince/weechat-fish#26]
This appears to be an ongoing issue for people, and while my cryptography skills are non existent, I figure it would at least be helpful to compile what's known into a single place so that those unfortunate souls coming from Google will have somewhere to start troubleshooting.

In short, python 3 appears to be causing the issue. You can check what version of python weechat is using by typing `/python version` from within weechat.

Here's the error, I'm getting:

		Traceback (most recent call last):
		  File "/Users/user/.weechat/python/fish.py", line 865, in fish_modifier_in_privmsg_cb
		    clean = blowcrypt_unpack(match.group(5), b)
		  File "/Users/user/.weechat/python/fish.py", line 460, in blowcrypt_unpack
		    raw = blowcrypt_b64decode(padto(rest.encode('utf-8'), 12).decode('utf-8'))
		  File "/Users/user/.weechat/python/fish.py", line 414, in blowcrypt_b64decode
		    right |= B64.index(p) << (i * 6)
		ValueError: substring not found

		=!= python: error in function "fish_modifier_in_privmsg_cb"

Same error that's been [plaguing people](https://github.com/freshprince/weechat-fish/issues/11) for 8 years.

I've gathered so far that the lack of the `substring` is getting flagged from blowcrypt/pycrypto, not the plugin since the term `substring` doesn't appear in the file.

Others have had [similar issues](http://5.9.10.113/26595855/python-irc-fish-encryption-issue) but in all cases there are no answers which leads me to believe there's something obvious I'm overlooking which, in the past, the questioner has thought [_"oops, that was obvious"_](https://media.giphy.com/media/COYGe9rZvfiaQ/giphy.gif) and simply removed or self-closed their issues, but I'm happy to be the proud dodo bird who leaves it up for future dodo birds.

I'm using `weechat` on macOS Big Sur (11.4)

It appears this is caused by using python v3. There's been a bunch of discussion about it: at [Pull Request #406](https://github.com/weechat/scripts/pull/406), as well as [Pull Request #398](https://github.com/weechat/scripts/pull/398). In both cases PR's were submitted that don't solve the issue for me.

I've been troubleshooting this for a few days now, and as frustrating as it's been, I also think this is a good opportunity to amalgamate the discussion to a single place so we can figure out what's not working, and iron it out.

**Comment by freshprince** [comment]
It seems like you're not using the version of this git repository. `blowcrypt_b64decode` is nowhere near [line 414](https://github.com/freshprince/weechat-fish/blob/master/fish.py#L414).

fish.py from weechat/scripts has taken on an life on its own and I'm not really that motivated provide support for it.

**Comment by jpgninja** [comment]
Appreciate the response.

I opened the Issue in the open source sense, so that someone hitting the same issue will have something searchable to stumble upon; not expecting a solution, though.

You're probably right that the pasted error comes from one of the alternatives PR's or the solutions in their comments, rather than this – sorry, that's sloppy. I'll go back and update the proper error. Regardless of line number the error is the same, and hits identical function chain so I have reason to believe the same issue is causing both.

Assuming it's a PEBKAC issue, I'll swing back and follow up with my resolution.

**Comment by h-0-s-h** [comment]
> Appreciate the response.
> 
> I opened the Issue in the open source sense, so that someone hitting the same issue will have something searchable to stumble upon; not expecting a solution, though.
> 
> You're probably right that the pasted error comes from one of the alternatives PR's or the solutions in their comments, rather than this. I'll go back and update the proper error. I should say, regardless of line number, the error is the same and hits identical function chain so I have reason to believe the same issue is causing both.
> 
> Assuming it's a PEBKAC issue, I'll swing back and follow up with my resolution.

Any update on this @jpgninja -- also seeing this issue with the fish.py from this repo, and even one of the forked copies I came across (https://github.com/mawashii/weechat-fish) has the same underlying error with UTF8.

I realize Blowfish in 2022 is sort of...counter-intuitive, but the only other option for us heavy IRC users that's remotely usable is a ZNC module ([Crypt](https://github.com/znc/znc/blob/master/modules/crypt.cpp)) but it only supports CBC mode and not ECB (which is still in widespread use unfortunately)...and requires loading another (older) ZNC module ([fish](https://github.com/znc/znc/blob/master/modules/crypt.cpp)) both of which store the keys in either plaintext or easily decryptable...right on the shell.

If there's any Python(3) guru's available to tackle a working weechat-fish.py for 2022 that supports CBC+ECB decryption and proper UTF-8 decryption support from Python3 (bonus points if keys can be saved in weechat's securedata system) would be awesome.
@mawashii
@freshprince

Maybe even a bounty or something is possible?

**Comment by jpgninja** [comment]
> Any update on this @jpgninja 

Sorry to be the bearer of bad news, I never got it working.

**Comment by freshprince** [comment]
If you're experiencing this problem with this version of fish could you please provide a traceback and maybe the whole encrypted message that caused the exception so that I can reproduce this problem?

I'm using this script to decrypt ECB & CBC and UTF8 without any problems. I never bothered to implement ECB encryption because the implementation is braindead and gives no improvement to CBC. If I get into a situation where I have to use ECB encryption I might implement it here but as long as I don't need it...

**Comment by jpgninja** [comment]
> If you're experiencing this problem with this version of fish could you please provide a traceback and maybe the whole encrypted message that caused the exception so that I can reproduce this problem?

Sure, I could probably setup a test environment sometime this week.

Specifically, what's missing from the one provided?

**Comment by freshprince** [comment]
It's not from the script from this repository and there's no reproduction. But I've actually meant to address @h-0-s-h who claimed he has this problem with this version.

**Comment by jpgninja** [comment]
No sweat, I'll leave you to it. Apologies for getting my wires crossed in the initial submission; I'd worked for weeks to resolve this since no one else was, and by the time I got to the point of submitting the Issue I'd already uninstalled the plugin and moved on.

Not trying to pass blame or make you feel attacked, but from the end-user's side of things, a: (a) fatal issue, (b) faced by multiple users, (c) in the same method, (d) trying to do the same thing, (e) going unresolved for over a decade, feels indistinguishable from being ignored. If we're still at the point where the Issue gets dismissed on the premise of _"that line number doesn't match up,"_ then there's not much to discuss.  The line number may have changed over the last ten years, but the bug hasn't. At some point a project's dev need to make _some_ sort of effort.

In either case, since you've decided the above info isn't enough – and since I've lost faith anyone will do anything about it – my intention/contribution was just to amalgamate everyone's research over the last decade into one place.

Good luck on this!

P.S. No hard feelings, I know how frustrating it can be to be a dev with a persistent-yet-unreproducible issue.

**Comment by freshprince** [comment]
Let me repeat myself for you: I do not provide end-user support for scripts that are not from this very repository. By posting here you will only reach me and none of the people that changed this script and released it themselves.

> The line number may have changed over the last ten years, but the bug hasn't. 

I don't really understand what you mean with 'the line numbers may have changed over the last ten years.' The last commit in this repository was in January this year and the last commit that added and removed lines was two years ago.

I actually like to prepare a new release but since this issue is still open I'm waited so that I could fix this problem if it really existed in this script.

But do you really expect me to help you with a problem with code that 

1. I didn't write
2. I don't use
3. I don't care about

without getting any pay from you?

I've written this script for myself so that I could communicate with my friends on IRC. Flashcode persuaded me to put the script on weechat.org/scripts which was a curse and a blessing. A blessing because I recieved valueable bug reports which made this script better and a curse because other people changed the script and reuploaded it. I didn't want to revert those changes over there because I don't care for the conflict but I also don't want to pull those changes into my repository for various reasons.

I am going to close this issue since as I already told you I'm using the script from this repository without any problems and I have no reason to believe that this bug exists in it.

But if it happens that you or anyone else find this problem with this very script then please feel free to reopen and provide me with the information that I've asked for so that I can fix it. Otherwise I can't help you and you're talking to the wrong guy.
